---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/theaspe9/public_html/
    - /bin/cp /home4/theaspe9/repositories/coming/index.html $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/css $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/images $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/include $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/js $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/one-page $DEPLOYPATH
    - /bin/cp -R /home4/theaspe9/repositories/coming/sass $DEPLOYPATH